import { PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn } from "typeorm";

/**
 * Core fields of entity
 *
 * @export
 * @abstract
 * @class Core
 */
export abstract class CoreEntity {
  /**
   * Entity autogenerated identifier
   *
   * @type {number}
   * @memberof Core
   */
  @PrimaryGeneratedColumn({ name: "id" })
  id: number;

  /**
   * Creation date
   *
   * @type {number}
   * @memberof Core
   */
  @CreateDateColumn({ name: "created" })
  created: Date;

  /**
   * Update date
   *
   * @type {number}
   * @memberof Core
   */
  @UpdateDateColumn({ name: "updated" })
  updated: Date;
}
